name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Обновлено до v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Обновлено до v5
      with:
        python-version: '3.10'  # Рекомендуется Python 3.10 для Kivy

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev
        pip install buildozer

    - name: Build APK
      run: |
        buildozer -v android debug
        mkdir apk
        cp bin/*.apk apk/

    - name: Upload APK
      uses: actions/upload-artifact@v4  # Обновлено до v4
      with:
        name: rocket-editor-apk
        path: apk
