name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          aidl
        pip install buildozer cython

    - name: Initialize Buildozer
      run: |
        buildozer init
        buildozer android update

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses.cfg
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses.cfg
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> ~/.android/licenses.cfg
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> ~/.android/licenses.cfg

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug
        mkdir apk
        cp bin/*.apk apk/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rocket-editor-apk
        path: apk
