name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          aidl \
          ant \
          unzip \
          openjdk-11-jdk \
          libtool \
          automake \
          autoconf \
          libffi-dev  # Add libffi-dev to prevent source build

    - name: Install Python dependencies
      run: |
        pip install buildozer cython python-for-android
        pip install --upgrade autoconf automake libtool  # Update build tools

    - name: Patch Python-for-Android
      run: |
        # Workaround for libffi build issues
        sed -i 's/AC_PROG_LIBTOOL/LT_INIT/g' $(find ~/.local -name "configure.ac" | grep libffi)
        sed -i 's/AC_HELP_STRING/AS_HELP_STRING/g' $(find ~/.local -name "configure.ac" | grep libffi)
        sed -i 's/AC_TRY_RUN/AC_RUN_IFELSE/g' $(find ~/.local -name "configure.ac" | grep libffi)
        sed -i 's/AC_TRY_LINK/AC_LINK_IFELSE/g' $(find ~/.local -name "configure.ac" | grep libffi)
        sed -i 's/AC_TRY_COMPILE/AC_COMPILE_IFELSE/g' $(find ~/.local -name "configure.ac" | grep libffi)

    - name: Initialize Buildozer environment
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses.cfg
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses.cfg
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> ~/.android/licenses.cfg
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> ~/.android/licenses.cfg

    - name: Build APK
      run: |
        # Use prebuilt libffi if available
        echo "[buildozer]" > ~/.buildozer/config.ini
        echo "p4a.local_recipes = " >> ~/.buildozer/config.ini
        echo "android.use_prebuilt_libffi = True" >> ~/.buildozer/config.ini
        
        buildozer -v android debug
        mkdir apk
        cp bin/*.apk apk/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rocket-editor-apk
        path: apk
